### ISSUE TITLE
Use port 80/443 for IPFS

### ISSUE THREAD

**Issue by bumi** [67P/kredits-web#124]
Currently we use port 5444 to connect to the IPFS node on ipfs.kosmos.org. Certain public wifis block such ports and thus kredits-web can not be loaded. 

Can we connect to the IPFS node on port 80/443?

**Comment by skddc** [comment]
It's possible. We've been doing this in order to keep a low profile with potential spammers, as there's currently no way for us to authenticate PUT requests to our IPFS node and all documents uploaded to it are pinned automatically.

However, if we implement [my suggestion for pinning from contract events](https://gitea.kosmos.org/kosmos/chef/issues/26#issuecomment-591), then this would be automatically solved as well. And not by obfuscation, but by actual verification. Which is yet another benefit of the approach, which I hadn't even thought about before.

**Comment by skddc** [comment]
Closing in favor of https://github.com/67P/kredits-contracts/issues/148

We already use the new gateway at `https://ipfs.kosmos.io` for GET requests. And we'll use local IPFS for creating and distributing new docs, as they are now automatically pinned remotely when they appear on the blockchain.
