### ISSUE TITLE
Implement caching of data

### ISSUE THREAD

**Issue by bumi** [67P/kredits-web#182]
Currently all the data is loaded from Ethereum and IPFS when accessing the page. We should cache data to speed up page loads and decrease the amount of data that is required to load each time.

This includes both data from Ethereum and from IPFS.

**Comment by skddc** [comment]
For IPFS, there is also another option: the [js-ipfs node](https://github.com/ipfs/js-ipfs/tree/master/examples/ipfs-101) implementation comes with its own IndexedDB cache, which was just improved [in the latest release](https://blog.ipfs.io/2020-05-21-js-ipfs-0-44/) as well.

So, instead of connecting to a separate remote or local node, we could also run an actual node directly in kredits-web, and have it cache its own data.

Alternatively, if we keep the current setup of connecting a normal go-ipfs node, we could at least use the same data model in IndexedDB, so that we could swap with a JS node in the future, and already have the cached data there.
